version: "3"

services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ttt
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432

