"""empty message

Revision ID: b069937b2ece
Revises: d8927ceb8d65
Create Date: 2023-06-10 12:02:02.130928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b069937b2ece'
down_revision = 'd8927ceb8d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###
