"""empty message

Revision ID: d831724a31c1
Revises: b069937b2ece
Create Date: 2023-06-10 12:35:30.079371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd831724a31c1'
down_revision = 'b069937b2ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.String(length=5), nullable=True))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.drop_column('outcome')

    # ### end Alembic commands ###
