"""empty message

Revision ID: d8927ceb8d65
Revises: eea53867a9d6
Create Date: 2023-06-09 18:50:09.107630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8927ceb8d65'
down_revision = 'eea53867a9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('game_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('game_end', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('games_player_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'])
        batch_op.drop_column('player_id')
        batch_op.drop_column('session')
        batch_op.drop_column('game_time')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('outcome',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('session', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('games_player_id_fkey', 'players', ['player_id'], ['id'])
        batch_op.drop_column('game_end')
        batch_op.drop_column('game_start')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
